# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d83c443875dc08218b4d9b1d555d2c0e61a425231f3c6b6cf9a90dda7d2c9841f09bf8ce5f76cf558e8dd88945f4ede6ada6c205294cd740b182a1595f8ca74

test:
  secret_key_base: 7b46d73192451f36ec86eda8ccfdc8eea0357f86ce63e6e2b7791e24fd3ff3991d7c20d4134780973e509d0acd1da9dd60f24186f15a377384ebd4f43dcf2200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
